{
 "title": "Engram Log Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top Warnings and Errors",
   "type": "timeseries",
   "description": "Top 10 count of errors and warning per minute grouped by message. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,sum(count_over_time({service=\"charon\"} | logfmt | level=~`(warn|error)` | label_format level=\"{{trunc 1 .level | upper}}\"[1m])) by (level,msg,topic))",
     "legendFormat": "{{level}} [{{topic}}] {{msg}}"
    }
   ]
  },
  {
   "title": "Duty Failed Reasons",
   "type": "logs",
   "description": "Reasons why duties failed prefixed by slot and duty type",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"charon\"} | logfmt | msg=`Duty failed` | line_format `{{.duty}}\t{{.reason}}`"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{service=\"charon\"} | logfmt | line_format \"{{upper .level | trunc 4 }} {{.topic}}\t{{.msg}}\t\t{{if .slot}}slot={{.slot}}{{end}}{{if .duty}}duty={{.duty}}{{end}}\""
    }
   ]
  }
 ]
}